### ISSUE TITLE
Container/ Content Alignment Issues

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect_P2#1]
Try zooming out your browser and you will see issues with the container/content width :)

**Comment by Mikerniker** [comment]
Hi Hart, I tried[ fixing the container](https://github.com/Mikerniker/CodeConnect_P2/commit/79c437804fe0f719c0b06c10803f3aa3008f537b), let me know if this is what you had in mind, thanks!

**Comment by hartpableo** [comment]
Much better. Although please review your implementation on the row class as it looks like it's being added to places that dont need it. Example:

![image](https://github.com/user-attachments/assets/9cc1195a-3f40-40ba-b7b1-88487470d12f)


Please remove unnecessary classes to avoid unnecessary complexities.

**Comment by Mikerniker** [comment]
Hi @hartpableo I removed the row class in some sections
