### ISSUE TITLE
Header covered on scroll

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect_P2#2]
![image](https://github.com/user-attachments/assets/b999fe8c-3f1e-4d86-880a-3ffcd0c99453)

Header is covered by the other elements

**Comment by Mikerniker** [comment]
Hi Hart, I tried making a [change to fix the header](https://github.com/Mikerniker/CodeConnect_P2/commit/a1a3435403d61b680655b608974d4671e91be993). Let me know if this is better.

**Comment by hartpableo** [comment]
You got it :)
