### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by hartpableo** [Mikerniker/CodeConnect_P2#3]
font not rendered/recognized

**Comment by Mikerniker** [comment]
Hi Hart, I tried [fixing the font import](https://github.com/Mikerniker/CodeConnect_P2/commit/9efae32f201629ffe1314772f6dbed5244499f2f) I'm not sure though if this is the issue for not rendering, currently it seems to render on my end. If it still doesn't work, I'll try to find another way. Thank you

**Comment by hartpableo** [comment]
Hi @Mikerniker try using the fonts inside the 'static' directory

**Comment by Mikerniker** [comment]
Hi @hartpableo I added the static fonts, let me know if this works better. Thanks!

**Comment by hartpableo** [comment]
Hi @Mikerniker you didnt link to your font-face.css that's why the fonts are still not rendering correctly

**Comment by Mikerniker** [comment]
ahh ok [added the links](https://github.com/Mikerniker/CodeConnect_P2/commit/72441707e712e350a708e7b2ffe060b89dd7d383), thanks @hartpableo !

**Comment by hartpableo** [comment]
Hi @Mikerniker one last thing, pls review the file path to your font-face.css in your index.html :)

**Comment by Mikerniker** [comment]
ok, missed that one, thanks @hartpableo , [its been updated](https://github.com/Mikerniker/CodeConnect_P2/commit/102fdc6938e6c53f331da91a5f87b99795dd7d50)
